"""Add encrypted device_identifier and credit_history to orders

Revision ID: f438025e6fdd
Revises: def60305cd45
Create Date: 2026-04-07 18:36:22.226750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f438025e6fdd'
down_revision = 'def60305cd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_device_identifier', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_credit_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('encrypted_credit_history')
        batch_op.drop_column('encrypted_device_identifier')

    # ### end Alembic commands ###
